# Generated by Django 5.2.7 on 2025-12-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_Amount',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
