# Generated by Django 5.2.7 on 2025-12-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_p_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='P_ID',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
