# Generated by Django 5.2.7 on 2025-12-29 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TID', models.CharField(max_length=20, null=True)),
                ('User_ID', models.CharField(max_length=20, null=True)),
                ('P_Name', models.CharField(max_length=20, null=True)),
                ('P_Amount', models.CharField(max_length=20, null=True)),
                ('P_Image', models.ImageField(null=True, upload_to='orderd_image')),
                ('Date_Time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
