# Generated by Django 5.2.7 on 2025-12-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=20, null=True)),
                ('U_Name', models.CharField(max_length=20, null=True)),
                ('U_Image', models.ImageField(default='user_details', null=True, upload_to='')),
                ('U_Email', models.CharField(max_length=20, null=True)),
                ('U_Password', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
