# Generated by Django 5.2.7 on 2025-12-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='U_PoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
