# Generated by Django 3.2.25 on 2026-03-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_detail_u_ponenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='U_Email',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='U_Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
