# Generated by Django 3.2.25 on 2026-03-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20260308_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='User_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
