# Generated by Django 3.2.25 on 2026-03-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_Name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
